version: "2"
services:
  codeceptio-container:
    container_name: codeceptio-container
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - chrome-container

  chrome-container:
    container_name: chrome-container
    image: selenium/standalone-chrome:3.12.0-americium
    ports:
      - "4444:4444"
