version: "2"
services:
  codeceptio-container:
    container_name: codeceptio-container
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - chrome-container
    volumes:
      - ./e2eTests:/e2eTests
      - ./package.json:/package.json
      - ./package-lock.json:/package-lock.json
      - ./.gitignore:/.gitignore
      - ./app.js:/app.js

  chrome-container:
    container_name: chrome-container
    image: selenium/standalone-chrome:3.12.0-americium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
